### ISSUE TITLE
Ajax Modal Support?

### ISSUE THREAD

**Issue by theshape** [wearerequired/required-foundation-reveal-shortcode#1]
Where is Modal Support for Ajax content?
Was it removed for WP reasons, while F4 still has it, or is it still being worked on and will be included in the final release?

**Comment by neverything** [comment]
The current version of the JS included in the release candidate is using Foundation 4.1.2 and since AJAX for reveal was added in 4.2 isn't yet included: http://foundation.zurb.com/docs/changelog.html

You can however update the Foundation in your themes locally: https://github.com/zurb/foundation/issues/1871#issuecomment-14882870 (only if you use the required+ Foundation 1.1 RC tags).

**Comment by grappler** [comment]
Closing this issue as the plugin has been deprecated.
